### ISSUE TITLE
Mongoose.connect() deprication issue

### ISSUE THREAD

**Issue by Dynamic-Gravity** [iamshaunjp/rest-api-playlist#5]
(node:10932) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/connections.html#use-mongo-client

This is resolved by:
```
mongoose.connect('mongodb://localhost/ninjago', {useMongoClient: true});
```

**Comment by pinglinh** [comment]
@Dynamic-Gravity I'm still getting this issue despite having added ` {useMongoClient: true}`
It's also saying `WARNING: The useMongoClient option is no longer necessary in mongoose 5.x, please remove it.` 

Also my post request isn't working in postman ... not sure what's going on

**Comment by Dynamic-Gravity** [comment]
@pinglinh A quick search says that latest mongoose is on version 5.0.1.

I am using version `"mongoose": "^4.13.9"`., and that is what my PR was for.

It seems to have changed again as of the 5.x version and will require additional tinkering.

Edit: I just updated my example to `"mongoose": "^5.0.1"` which should be the same version you're using and the server started without issue and I was able to make POST requests. I did get the same warning you did, removed the `useMongoClient` option, and then it worked as expected. I'm not sure why your POST requests arn't working but it is not related to this updated mongoose version.

Seeing as how the latest version of mongoose no longer needs this fix, I think I'm going to cancel this PR as it's no longer relevant.

**Comment by pinglinh** [comment]
@Dynamic-Gravity Ok thanks for your help. I'm not sure whether it's windows problem sigh. I will try on mac later on and see if the problem still persists. After clicking send on postman, it keeps loading and takes a while before it can't get any response. Perhaps something is wrong with my code...

**Comment by Dynamic-Gravity** [comment]
@pinglinh If something is wrong with the code you can post a gist. I would make a separate thread about that though. You can pm here or on Discord (where I hangout). `DynamicGravity #1132`

**Comment by Dynamic-Gravity** [comment]
For anyone of the future reading this, the Mongoose package no longer needs you to manually specify the `{useMongoClient: true}` option as of `^5.0.1`.

If you are using a version less than that, like `^4.13.9` then you will need to specify the option.
